import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ArrowUpRight, X } from 'lucide-react';
import { CASES_DATA } from '../data/portfolioData';

export const CasesTab: React.FC = () => {
 const [selected,setSelected]=useState<(typeof CASES_DATA)[number]|null>(null);
 return <div className="lux-page py-5 sm:py-10">
  <header className="grid gap-8 border-b border-[#D8D0C2] pb-12 dark:border-white/10 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="lux-kicker">Selected Matters · Representative Work</p><h2 className="lux-title mt-5">案例不展示喧哗，<br/><span className="text-[#987B47] dark:text-[#C9A86A]">只展示判断如何产生价值。</span></h2></div><p className="text-sm leading-7 text-[#77736B] dark:text-[#99958D]">以下项目均以脱敏方式呈现，重点说明问题、方法与结果，不披露客户、金额或内部商业信息。</p></header>
  <div className="mt-12 space-y-5">{CASES_DATA.map((c,i)=><motion.button key={c.id} onClick={()=>setSelected(c)} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:i*.05}} className="group grid w-full overflow-hidden border border-[#D8D0C2] bg-[#FDFCF9] text-left transition-all hover:border-[#B89F6B] hover:shadow-[0_20px_60px_rgba(30,34,43,.08)] dark:border-white/10 dark:bg-[#1C1C1E] md:grid-cols-[.42fr_.58fr]">
    <div className="relative min-h-56 overflow-hidden bg-[#DED7CA]"><img src={c.coverImage} alt="案例视觉" className="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.025]"/><div className="absolute inset-0 bg-[#172033]/20"/><span className="absolute left-5 top-5 border border-white/50 bg-black/20 px-3 py-1 text-[9px] uppercase tracking-[.18em] text-white backdrop-blur">Case 0{i+1}</span></div>
    <div className="flex flex-col justify-between p-7 sm:p-10"><div><div className="flex flex-wrap gap-3 text-[10px] uppercase tracking-[.14em] text-[#9A958D]"><span>{c.industry}</span><span>·</span><span>{c.type}</span><span>·</span><span>{c.year}</span></div><h3 className="mt-5 font-serif text-2xl font-normal leading-tight sm:text-3xl">{c.title}</h3><p className="mt-3 text-sm text-[#987B47] dark:text-[#C9A86A]">{c.subtitle}</p><p className="mt-6 line-clamp-3 text-sm leading-7 text-[#77736B] dark:text-[#99958D]">{c.summary}</p></div><div className="mt-8 flex items-end justify-between"><div className="flex flex-wrap gap-2">{c.tags.slice(0,3).map(t=><span key={t} className="text-[10px] text-[#8E8980]">#{t.replace(/^#/,'')}</span>)}</div><ArrowUpRight size={19} className="text-[#9B7B42] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1"/></div></div>
  </motion.button>)}</div>
  <AnimatePresence>{selected&&<motion.div className="fixed inset-0 z-[100] flex items-end justify-center bg-[#0E1420]/70 p-0 backdrop-blur-sm sm:items-center sm:p-6" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSelected(null)}><motion.article initial={{y:40,opacity:0}} animate={{y:0,opacity:1}} exit={{y:30,opacity:0}} onClick={e=>e.stopPropagation()} className="max-h-[92vh] w-full max-w-4xl overflow-y-auto bg-[#F8F5EE] p-7 text-[#172033] shadow-2xl dark:bg-[#171B23] dark:text-[#F2EDE3] sm:p-11"><div className="flex justify-between gap-6"><div><p className="lux-kicker">Case Detail · 脱敏项目</p><h3 className="mt-4 font-serif text-3xl">{selected.title}</h3><p className="mt-2 text-sm text-[#987B47]">{selected.subtitle}</p></div><button onClick={()=>setSelected(null)} aria-label="关闭"><X size={22}/></button></div><div className="mt-9 grid gap-8 sm:grid-cols-2"><section><p className="lux-kicker">Context</p><p className="mt-3 text-sm leading-7 text-[#706C64] dark:text-[#A7A299]">{selected.background}</p></section><section><p className="lux-kicker">Challenge</p><p className="mt-3 text-sm leading-7 text-[#706C64] dark:text-[#A7A299]">{selected.challenge}</p></section></div><section className="mt-9 border-t border-[#D8D0C2] pt-7 dark:border-white/10"><p className="lux-kicker">Legal Approach</p><ol className="mt-4 grid gap-3 sm:grid-cols-2">{selected.actions.map((a,i)=><li key={a} className="flex gap-3 text-sm leading-6"><span className="font-serif text-[#A88E5E]">0{i+1}</span><span>{a}</span></li>)}</ol></section><section className="mt-9 grid gap-px bg-[#D8D0C2] dark:bg-white/10 sm:grid-cols-3">{selected.results.map(r=><div key={r.label} className="bg-white/65 p-5 dark:bg-[#1C212B]"><strong className="font-serif text-2xl font-normal text-[#8D754B]">{r.value}</strong><p className="mt-2 text-xs font-medium">{r.label}</p><p className="mt-1 text-[10px] text-[#8B867D]">{r.subtext}</p></div>)}</section></motion.article></motion.div>}</AnimatePresence>
 </div>;
};
