import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ArrowUpRight, X } from 'lucide-react';
import { INSIGHTS_DATA } from '../data/portfolioData';

export const InsightsTab: React.FC = () => {
 const [article,setArticle]=useState<(typeof INSIGHTS_DATA)[number]|null>(null);
 return <div className="lux-page py-5 sm:py-10">
  <header className="border-b border-[#D8D0C2] pb-12 dark:border-white/10"><p className="lux-kicker">Insights · Legal Thinking</p><div className="mt-5 grid gap-7 lg:grid-cols-[1fr_.62fr] lg:items-end"><h2 className="lux-title">观点的价值，<br/><span className="text-[#987B47] dark:text-[#C9A86A]">在于帮助下一次判断。</span></h2><p className="text-sm leading-7 text-[#77736B] dark:text-[#99958D]">记录企业法务、零售合规与商业交易中的长期问题。少做结论堆砌，多解释判断框架。</p></div></header>
  <div className="mt-12 grid gap-5 lg:grid-cols-12">{INSIGHTS_DATA.map((a,i)=><motion.button key={a.id} onClick={()=>setArticle(a)} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.04}} className={`${i===0?'lg:col-span-8':'lg:col-span-4'} group flex min-h-[300px] flex-col justify-between border border-[#D8D0C2] bg-[#FDFCF9] p-7 text-left transition-all hover:border-[#B89F6B] dark:border-white/10 dark:bg-[#1C1C1E] sm:p-9`}><div><div className="flex items-center justify-between text-[10px] uppercase tracking-[.14em] text-[#99948B]"><span>{a.date}</span><span>{a.readTime}</span></div><h3 className={`${i===0?'text-3xl sm:text-4xl':'text-2xl'} mt-10 font-serif font-normal leading-tight group-hover:text-[#987B47]`}>{a.title}</h3><p className="mt-5 text-sm leading-7 text-[#77736B] dark:text-[#99958D]">{a.summary}</p></div><div className="mt-8 flex items-end justify-between"><div className="flex flex-wrap gap-2">{a.tags.slice(0,3).map(t=><span key={t} className="text-[10px] text-[#9B7B42]">{t}</span>)}</div><ArrowUpRight size={18} className="text-[#9B7B42] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1"/></div></motion.button>)}</div>
  <div className="mt-14 border-y border-[#D8D0C2] py-8 text-center dark:border-white/10"><p className="font-serif text-xl leading-8 text-[#454B5A] dark:text-[#D6D0C5]">“判断力来自持续复盘，而不是一次正确。”</p><p className="mt-2 text-[9px] uppercase tracking-[.2em] text-[#A09A90]">A working note on legal practice</p></div>
  <AnimatePresence>{article&&<motion.div className="fixed inset-0 z-[100] overflow-y-auto bg-[#F8F5EE] text-[#172033] dark:bg-[#141820] dark:text-[#F2EDE3]" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="mx-auto max-w-3xl px-6 py-12 sm:px-10 sm:py-20"><button onClick={()=>setArticle(null)} className="fixed right-6 top-6 rounded-full border border-[#D2CABD] bg-[#F8F5EE]/90 p-3 dark:border-white/10 dark:bg-[#141820]/90" aria-label="关闭"><X size={20}/></button><p className="lux-kicker">{article.date} · {article.readTime}</p><h1 className="mt-6 font-serif text-4xl font-normal leading-tight sm:text-5xl">{article.title}</h1><p className="mt-7 text-lg leading-8 text-[#706C64] dark:text-[#AAA59C]">{article.lead}</p><div className="prose-lux mt-12 space-y-7">{article.contentParagraphs.map((p,i)=><p key={i} className="text-base leading-8 text-[#4F5360] dark:text-[#C4BEB4]">{p}</p>)}</div><blockquote className="my-12 border-y border-[#CBB98E] py-8 text-center font-serif text-2xl leading-10 text-[#7F683F] dark:text-[#D9C08F]">“{article.quote.text}”</blockquote>{article.clauseExample&&<section className="bg-[#EEE8DC] p-6 dark:bg-[#1C222C]"><p className="lux-kicker">{article.clauseExample.title}</p><pre className="mt-4 whitespace-pre-wrap font-mono text-xs leading-6">{article.clauseExample.code}</pre><p className="mt-4 text-sm leading-7 text-[#706C64] dark:text-[#AAA59C]">{article.clauseExample.explanation}</p></section>}</div></motion.div>}</AnimatePresence>
 </div>;
};
