import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { MapPin, X } from 'lucide-react';
import { NOTES_DATA } from '../data/portfolioData';

export const NotesTab: React.FC = () => {
 const [selected,setSelected]=useState<(typeof NOTES_DATA)[number]|null>(null);
 return <div className="lux-page py-5 sm:py-10">
  <header className="grid gap-8 border-b border-[#D8D0C2] pb-12 dark:border-white/10 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="lux-kicker">Notes · Life Beyond Work</p><h2 className="lux-title mt-5">工作之外，<br/><span className="text-[#987B47] dark:text-[#C9A86A]">保留观察世界的细节。</span></h2></div><p className="text-sm leading-7 text-[#77736B] dark:text-[#99958D]">阅读、城市、器物与途中所见。不是履历的延伸，而是专业判断背后的生活质地。</p></header>
  <div className="mt-12 columns-1 gap-5 sm:columns-2 lg:columns-3">{NOTES_DATA.map((n,i)=><motion.button key={n.id} onClick={()=>setSelected(n)} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.04}} className="group mb-5 block w-full break-inside-avoid overflow-hidden border border-[#D8D0C2] bg-[#FDFCF9] text-left dark:border-white/10 dark:bg-[#091A2E]"><div className={`relative overflow-hidden ${i%3===0?'aspect-[4/5]':'aspect-[4/3]'}`}><img src={n.image} alt="日常记录" className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.025]"/><div className="absolute inset-0 bg-gradient-to-t from-[#101827]/35 to-transparent opacity-60"/></div><div className="p-5"><div className="flex items-center justify-between text-[9px] uppercase tracking-[.14em] text-[#99948B]"><span>{n.date}</span><span className="flex items-center gap-1"><MapPin size={10}/>{n.location}</span></div><p className="mt-4 line-clamp-3 text-sm leading-7 text-[#64625D] dark:text-[#AAA69E]">{n.caption}</p><div className="mt-4 flex flex-wrap gap-2">{n.tags.map(t=><span key={t} className="text-[9px] text-[#9B7B42]">{t}</span>)}</div></div></motion.button>)}</div>
  <AnimatePresence>{selected&&<motion.div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#0E1420]/85 p-5 backdrop-blur-md" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSelected(null)}><motion.div initial={{scale:.97,opacity:0}} animate={{scale:1,opacity:1}} exit={{scale:.98,opacity:0}} onClick={e=>e.stopPropagation()} className="grid max-h-[90vh] w-full max-w-5xl overflow-hidden bg-[#F8F5EE] text-[#172033] dark:bg-[#171B23] dark:text-[#F2EDE3] md:grid-cols-[1.25fr_.75fr]"><img src={selected.image} alt="日常记录大图" className="h-full max-h-[60vh] w-full object-cover md:max-h-[82vh]"/><div className="relative flex flex-col justify-between p-7 sm:p-9"><button onClick={()=>setSelected(null)} className="absolute right-5 top-5" aria-label="关闭"><X size={20}/></button><div><p className="lux-kicker">{selected.date}</p><p className="mt-10 font-serif text-xl leading-9">{selected.caption}</p></div><div className="mt-8 border-t border-[#D8D0C2] pt-5 text-xs text-[#8D8982] dark:border-white/10"><p className="flex items-center gap-2"><MapPin size={13}/>{selected.location}</p><div className="mt-3 flex gap-2 text-[#9B7B42]">{selected.tags.map(t=><span key={t}>{t}</span>)}</div></div></div></motion.div></motion.div>}</AnimatePresence>
 </div>;
};
